Init project
MENDEL-BA/mainaProjetc pull request #2
Opened 2023-11-03 15:59 UTC by Maimouna1-WONE

2023-11-04 11:46 UTC, MENDEL-BA reviewed
Dans l'ensemble le projet est bon

2023-11-04 11:46 UTC, MENDEL-BA commented on .mvn/wrapper/maven-wrapper.jar
Pas besoin d'etre commit

2023-11-04 11:46 UTC, MENDEL-BA commented on .mvn/wrapper/maven-wrapper.properties
pas besoin d'etre commite non plus

2023-11-04 11:46 UTC, MENDEL-BA commented on .mvn/wrapper/maven-wrapper.jar
Tous le dossier .mvn et son contenu ne doivent pas etre commite

2023-11-04 11:46 UTC, MENDEL-BA commented on src/main/java/com/institution/school/controllers/RoomController.java
> +@RequestMapping(value = "/api/room")
Les URI sont toujours au pluriel par convention

2023-11-04 11:46 UTC, MENDEL-BA commented on src/main/java/com/institution/school/dtos/RoomDTO.java
utilisation des collections pour stocker des objets. Si cela correspond à votre modèle métier, c'est correct. Cependant, il est important de noter que si vous avez beaucoup de données dans ces collections, cela peut affecter les performances lors de la sérialisation/désérialisation en tant qu'objet JSON, en particulier si les collections sont profondément imbriquées. 
ajouter des constructeurs pour initialiser des objets RoomDTO. Par exemple, un constructeur sans arguments pour créer des instances vides, et un constructeur prenant les valeurs nécessaires pour initialiser l'objet.

2023-11-04 11:46 UTC, MENDEL-BA commented on src/main/java/com/institution/school/models/Room.java
> +    @Column(unique = true)
Ajoutez des validations assurer que les données sont correctes en fonction des règles métier,utiliser des annotations de validation, telles que @NotBlank ou @NotNull, pour garantir que les propriétés requises ne sont pas nulles ou vides.
@Column(unique = true)
@NotBlank
private String name;

2023-11-04 11:46 UTC, MENDEL-BA commented on src/main/java/com/institution/school/models/Room.java
> +    private Collection<Teacher> teachers;
Utilisation de Set au lieu de Collection : Utilisez l'interface Set plutôt que l'interface Collection pour les propriétés qui doivent contenir des éléments uniques (comme  Teachers).
@ManyToMany(mappedBy = "rooms", fetch = FetchType.EAGER)
private Set<Teacher> teachers = new HashSet<>();

2023-11-04 11:46 UTC, MENDEL-BA commented on src/main/java/com/institution/school/models/Room.java
> +    private Collection<Session> sessions = new ArrayList<>();
@OneToMany(mappedBy = "room")
private Set<Session> sessions = new HashSet<>();
On peut ajouter des annotations JPA comme @OneToMany si cela correspond mieux a notre modèle de données.

2023-11-04 11:46 UTC, MENDEL-BA commented on src/main/java/com/institution/school/models/Room.java
> +public class Room {
on peut ajouter des méthodes pour ajouter et supprimer des éléments de vos collections, ce qui permet un meilleur contrôle sur les opérations.
public void addTeacher(Teacher teacher) {
    this.teachers.add(teacher);
    teacher.getRooms().add(this);
}

public void removeTeacher(Teacher teacher) {
    this.teachers.remove(teacher);
    teacher.getRooms().remove(this);
}

Et on pourrait utliser ces methodes dans nos services comme ceci :
@Service
public class RoomService {
    @Autowired
    private RoomRepository roomRepository;

    public Room addTeacherToRoom(Long roomId, Teacher teacher) {
        Room room = roomRepository.findById(roomId)
                .orElseThrow(() -> new EntityNotFoundException("Room not found"));

        room.addTeacher(teacher);
        return roomRepository.save(room);
    }
}
@Service
public class RoomService {
    @Autowired
    private RoomRepository roomRepository;

    public Room removeTeacherFromRoom(Long roomId, Teacher teacher) {
        Room room = roomRepository.findById(roomId)
                .orElseThrow(() -> new EntityNotFoundException("Room not found"));

        room.removeTeacher(teacher);
        return roomRepository.save(room);
    }
}

2023-11-04 11:46 UTC, MENDEL-BA commented on src/main/java/com/institution/school/services/RoomServiceImpl.java
> +@Service
Ajouter un sous package dans services et l'appeller serviceImpl qui contiendrait tes implementations

2023-11-04 11:46 UTC, MENDEL-BA commented on src/main/resources/application.yml
> +server:
Mettre des variables d'environnement pour ne pas exposer ces identifiants de connection, si tu utilises intellij je te montrerais

2023-11-04 11:47 UTC, MENDEL-BA reviewed
Apporter les modifications

2023-11-04 11:48 UTC, MENDEL-BA requested changes
Apporter les modifications que j'ai mise en commentaire

2023-11-12 11:17 UTC, Maimouna1-WONE commented
Hello Mendel, je me sens perdue par rapport à ce que je dois faire.
Si tu peux me faire une check list en ce sens.
Merci.

*Maimouna WONE*
Application Developer
M: + 221 (77) 746 09 00
Hann village à côté de la grande mosquée

Dakar, Senegal


Le dim. 5 nov. 2023 à 17:43, Mendel Ba ***@***.***> a écrit :

> Closed #2 <https://github.com/MENDEL-BA/mainaProjetc/pull/2>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MENDEL-BA/mainaProjetc/pull/2#event-10865478676>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO2VUKDSHBM4ER3XC6Z7OXTYC7F4NAVCNFSM6AAAAAA64UZEPSVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJQHA3DKNBXHA3DONQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-11-12 15:31 UTC, MENDEL-BA commented
Salut, ah je vois , en faite les commentaires dans les pulls requests dans chaque classe est la modification que tu dois apporter.
Par exemple si tu regardes qui concerne la classe Room. java https://github.com/MENDEL-BA/mainaProjetc/pull/2#discussion_r1382378054 est l'amelioration que tu apporter à cette classe.

2023-11-19 17:07 UTC, MENDEL-BA commented on .DS_Store
ce fichier sur .gitignore

2023-11-19 17:08 UTC, MENDEL-BA commented on .jpb/jpb-settings.xml
ajouter aussi sur le .gitignore

2023-11-19 17:08 UTC, MENDEL-BA commented on .mvn/wrapper/maven-wrapper.jar
ajouter aussi sur le .gitignore

2023-11-19 17:41 UTC, merged